import Layout from "@/components/Layout";
import ProductItem from "@/components/product/ProductItem";
import { IProductModel } from "@/models/Product";
import { BASE_URL } from "@/utils/globals";
import axios from "axios";
import Cookies from "js-cookie";
import Head from "next/head";
import { useState } from 'react';
const baseUrl = BASE_URL || process.env.BASE_URL;
interface IProps {
    products: IProductModel[], result: number,
}
export default function Home(props:IProps){
    const [products, setProducts] = useState(props.products)
    console.log(products)
    return (
        <>
            <Head>
                <title>Tahawy Shop - Home Page</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Layout>
                <div className="grid justify-items-center grid-cols-1 gap-8 md:grid-cols-2 lg:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">{products.length === 0 ? <h1 className="text-3xl font-bold underline">No Products!</h1> : products.map((product:IProductModel) => (<ProductItem key={product._id} product={product} />))}</div>
            </Layout>
        </>
    );
}


export async function getServerSideProps() {
    const { data } = await axios.get(`${baseUrl}/api/product`)
    return {
        props: { products: data.products, result: data.result }, // will be passed to the page component as props
    }
}