import {useRef} from "react";
import {Toast} from "primereact/toast";
import {Button} from "primereact/button";
import Head from "next/head";

const Product = () => {
    const toast = useRef < Toast > (null);

    const showToast = () => {
        toast.current ?. show({severity: "info", summary: "Info", detail: "Message Content"});
    };
    return (
        <>
            <Head>
                <title>Product</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <div>
                <p className="text-4xl font-extrabold">Product</p>
                <Toast ref={toast}
                    position="bottom-right"/>
                <Button onClick={showToast}
                    label="Show"/>
            </div>
        </>
    );
};

export default Product;
