/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import React, {useRef, useState} from "react";
import {Button} from "primereact/button";
import Link from "next/link";
import {IFormEvent, InputChange} from "@/utils/Typescript";
import {useDispatch} from "react-redux";
import {AppDispatch} from "@/store";
import axios from "axios";
import {getError} from "@/utils/error";
import {startLoading, stopLoading} from "@/slices/globalSlice";
import {toast} from "react-toastify";
import {validEmail} from "@/utils/valid";
import {BASE_URL} from "@/utils/globals";
import Layout from "@/components/Layout";
import Image from "next/image";

const Register = () => {

    const initalState = {
        name: "",
        email: "",
        password: "",
        confirmPassword: ""
    };

    const dispatch: AppDispatch = useDispatch();

    const [userData, setUserData] = useState(initalState);
    const handleInputChange = ({target} : InputChange) => {
        const {name, value} = target;
        setUserData({
            ...userData,
            [name]: value
        });
    };

    function containsUppercase(str : string) {
        return /[A-Z]/.test(str);
    }
    function containsLowercase(str : string) {
        return /[a-z]/.test(str);
    }

    function containsNumbers(str : string) {
        return /[0-9]/.test(str);
    }
    const handleSubmit = async (e : IFormEvent) => {
        e.preventDefault();

        if (!userData.name) 
            return toast.warning(`Name isn't exist`);
        


        if (!validEmail(userData.email)) 
            return toast.warning(`Email isn't valid`);
        


        if (userData.password !== userData.confirmPassword) 
            return toast.warning(`Passwords doesn't match.`);
        


        if (userData.password.length < 8 || userData.confirmPassword.length < 8) 
            return toast.warning(`Passwords must be at least 8 chars.`);
        


        if (! containsNumbers(userData.password)) {
            return toast.warning("Passwords must be at least one numeric.");
        }
        if (! containsUppercase(userData.password)) {
            return toast.warning("Passwords must be at one uppercase.");
        }
        if (! containsLowercase(userData.password)) {
            return toast.warning("Passwords must be at one lowercase");
        }

        dispatch(startLoading());
        try {
            const {data, status} = await axios.post(`${BASE_URL}/api/auth/register`, userData);
            if (status === 200) {
                toast.success(data.msg);
            }
        } catch (error) {
            toast.error(getError(error));
        }
        dispatch(stopLoading());
    };

    return (
        <div>
            <Head>
                <title>Register</title>
                <meta name="description" content="Generated by create next app"/>
                <meta name="viewport" content="width=device-width, initial-scale=1"/>
                <link rel="icon" href="/favicon.ico"/>
            </Head>
            <Layout>
            <div className="flex justify-center">
            <Image className="hidden md:block" src="https://www.linkpicture.com/q/undraw_sign_up_nm4k.svg" alt="" width={500} height={500} />
            <div className="flex justify-center items-center h-screen flex-col">
                <div className="card flex justify-center items-center flex-wrap flex-col">
                    <h3 className="text-gray-500 text-3xl my-3">Register</h3>
                    <form onSubmit={handleSubmit}
                        className="flex flex-col gap-6">
      
                        <div className="form-control">
                                <label className="label">
                                    <span className="label-text">Your Name</span>
                                </label>
                                <input type="text" onChange={handleInputChange} name="name" placeholder="Ali" className="input input-bordered w-72" />
                            </div>
                        <div className="form-control">
                                <label className="label">
                                    <span className="label-text">Your Email</span>
                                </label>
                                <input type="email" onChange={handleInputChange} name="email" placeholder="info@site.com" className="input input-bordered w-72" />
                            </div>
                            <div className="form-control">
                                <label className="label">
                                    <span className="label-text">Your Password</span>
                                </label>
                                <input type="password" onChange={handleInputChange} name="password" placeholder="*******" className="input input-bordered w-72" />
                            </div>
                            <div className="form-control">
                                <label className="label">
                                    <span className="label-text">Your Confirm Password</span>
                                </label>
                                <input type="password" onChange={handleInputChange} name="confirmPassword" placeholder="*******" className="input input-bordered w-72" />
                            </div>
                        {/* <Password className={`w-80`} value={value} onChange={(e) => setValue(e.target.value)} header={header} footer={footer} /> */}
                        <Button type="submit" label="Register"/>
                    </form>
                    <p className="mt-3">
                        Already have an account?{" "}
                        <Link href="/signin" className="text-red-500 font-bold hover:underline">
                            Login Now
                        </Link>
                    </p>
                </div>
            </div>
            </div>

            </Layout>
        </div>
    );
};

export default Register;
