/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import React, { useRef, useState } from "react";
import { InputText } from "primereact/inputtext";
import { Button } from "primereact/button";
import { Toast } from "primereact/toast";
import Link from "next/link";
import { Password } from "primereact/password";
import { Divider } from "primereact/divider";

const Signin = () => {
  const toast = useRef<Toast>(null);

  const handleSubmit = () => {};

  const show = () => {
    toast.current?.show({
      severity: "success",
      summary: "Form Submitted",
      detail: "Form Submitted",
    });
  };
  const [value, setValue] = useState("");
  const header = <div className="font-bold mb-3">Pick a password</div>;
  const footer = (
    <>
      <Divider />
      <p className="mt-2">Suggestions</p>
      <ul className="pl-2 ml-2 mt-0 line-height-3">
        <li>At least one lowercase</li>
        <li>At least one uppercase</li>
        <li>At least one numeric</li>
        <li>Minimum 8 characters</li>
      </ul>
    </>
  );

  return (
    <div>
      <Toast ref={toast} position="bottom-right" />
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center my-56 flex-col">
        <div className="card flex justify-center items-center flex-wrap flex-col">
          <h3 className="text-gray-500 text-3xl my-3">Sign in</h3>
          <form onSubmit={handleSubmit} className="flex flex-col gap-6">
            <span className="p-float-label">
              <InputText id="email" name="email" className={`w-80`} />
              <label htmlFor="email">Email</label>
            </span>
            <span className="p-float-label">
              <Password
                value={value}
                onChange={(e) => setValue(e.target.value)}
                feedback={false}
                toggleMask
              />
              <label htmlFor="password">Password</label>
            </span>
            {/* <Password className={`w-80`} value={value} onChange={(e) => setValue(e.target.value)} header={header} footer={footer} /> */}
            <Button type="submit" label="Sign in" />
          </form>
          <p className="mt-3">
            You don't have an account?{" "}
            <Link
              href="/register"
              className="text-red-500 font-bold hover:underline"
            >
              Register Now
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Signin;
