/* eslint-disable react/no-unescaped-entities */
import Head from "next/head";
import React, { useRef, useState } from "react";
import { InputText } from "primereact/inputtext";
import { Button } from "primereact/button";
import { Toast } from "primereact/toast";
import Link from "next/link";
import { Password } from "primereact/password";
import { Divider } from "primereact/divider";
import { validEmail } from "@/utils/valid";
import { toast } from "react-toastify";
import { useDispatch } from "react-redux";
import { AppDispatch } from "@/store";
import { login } from "@/slices/authSlice";
import { startLoading, stopLoading } from "@/slices/globalSlice";
import { IFormEvent, InputChange } from "@/utils/Typescript";
import Cookies from "js-cookie";
// import { setCookie } from "@/utils/globals";
// function setCookie(
//   cname: string,
//   cvalue: string,
//   exdays: number,
//   path: string = "/"
// ) {
//   const d = new Date();
//   d.setTime(d.getTime() + exdays * 24 * 60 * 60 * 1000);
//   let expires = "expires=" + d.toUTCString();
//   // document.cookie = `${cname}=${cvalue};${expires};path=${path};`;
//   document.cookie = cname + "=" + cvalue + ";" + expires + ";path=" + path;
// }

const Signin = () => {
  const [rfToken, setRfToken] = useState("");
  const dispatch: AppDispatch = useDispatch();
  const handleSubmit = async (e: IFormEvent) => {
    e.preventDefault();
    if (!userData.email) return toast.warning(`Email isn't exist.`);
    if (!validEmail(userData.email)) return toast.warning(`Email isn't valid`);
    if (!userData.password) return toast.warning(`Password isn't exist.`);
    if (userData.password.length < 8)
      return toast.warning(`Password must be at least 6 chars.`);
    dispatch(startLoading());

    await dispatch(login(userData));

    dispatch(stopLoading());
  };

  const handleInputChange = ({ target }: InputChange) => {
    const { name, value } = target;
    setUserData({ ...userData, [name]: value });
  };

  const [userData, setUserData] = useState({ email: "", password: "" });
  const header = <div className="font-bold mb-3">Pick a password</div>;
  const footer = (
    <>
      <Divider />
      <p className="mt-2">Suggestions</p>
      <ul className="pl-2 ml-2 mt-0 line-height-3">
        <li>At least one lowercase</li>
        <li>At least one uppercase</li>
        <li>At least one numeric</li>
        <li>Minimum 8 characters</li>
      </ul>
    </>
  );

  return (
    <div>
      <Head>
        <title>Sign in</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex justify-center my-56 flex-col">
        <div className="card flex justify-center items-center flex-wrap flex-col">
          <h3 className="text-gray-500 text-3xl my-3">Sign in</h3>
          <form onSubmit={handleSubmit} className="flex flex-col gap-6">
            <span className="p-float-label">
              <InputText
                id="email"
                name="email"
                className={`w-80`}
                onChange={handleInputChange}
              />
              <label htmlFor="email">Email</label>
            </span>
            <span className="p-float-label">
              <Password
                id="password"
                name="password"
                onChange={handleInputChange}
                toggleMask
                header={header}
                footer={footer}
              />
              <label htmlFor="password">Password</label>
            </span>
            {/* <Password className={`w-80`} value={value} onChange={(e) => setValue(e.target.value)} header={header} footer={footer} /> */}
            <Button type="submit" label="Sign in" />
          </form>
          <p className="mt-3">
            You don't have an account?{" "}
            <Link
              href="/register"
              className="text-red-500 font-bold hover:underline"
            >
              Register Now
            </Link>
          </p>
        </div>
      </div>
    </div>
  );
};

export default Signin;
